common:
    version: "0.1"
    server:
        host: "localhost"
        port: 5555
    log:
        conf: "logging_prod.yaml"
    aws:
        url: "https://{}.s3-ap-northeast-1.amazonaws.com/{}"
    mm_division:
        file_path: "/../../data/mm_division/division.json"
